package Common;

public enum MessageType
{
    /**
     * Hostess message types
     */
    PREPARE_FOR_PASS_BOARDING, WAIT_FOR_NEXT_FLIGHT, GET_N_PASSENGERS, WAIT_FOR_NEXT_PASSENGER, CHECK_DOCUMENTS, INFORM_PLANE_READY_TAKEOFF, CHECK_QUEUE_EMPTY,


    /**
     * Passenger message types
     */
    WAIT_IN_QUEUE, BOARD_THE_PLANE, WAIT_END_FLIGHT, LEAVE_PLANE, SHOW_DOCUMENTS,

    /**
     * Pilot message types
     */
    PARK_AT_TRANSFER_GATE, INFORM_PLANE_READY_BOARDING, WAIT_FOR_ALL_IN_BOARD, FLY_TO_DESTINATION, SET_AT_DESTINATION, ANNOUNCE_ARRIVAL, FLY_TO_DEPARTURE, GET_TOTAL_PASSENGERS,

    /**
     * General Repository types
     */

    PASSENGER_STATE, PILOT_STATE, HOSTESS_STATE, NEXT_FLIGHT, WRITE_LOG, END_REPORT,

    /**
     * Control types
     */

    OK

}
